---
- name: Detect Docker
  shell: /bin/grep -q "docker" /proc/1/cgroup
  register: docker_installed
  ignore_errors: True

- name: Docker Message
  debug: msg="This host is running inside a docker container"
  when: docker_installed.rc == 0

# TODO: var this

# == Prep ==
- name: Ensure /etc/nginx directory exists for configurations
  file: path=/etc/nginx state=directory

# == OS ==
- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

# == Install ==
- name: Checking installed version of nginx
  shell: /usr/bin/test "$({{nginx_daemon}} -v 2> /dev/null)" = "{{nginx_reported_version}}"
  register: wanted_version_installed
  ignore_errors: True
  changed_when: wanted_version_installed.rc == 1

- name: Download nginx {{nginx_file_tag}}
  get_url: url={{nginx_tarball_url}} dest={{nginx_tmp_dir}}{{nginx_file_name}}
  when: wanted_version_installed.rc == 1

# TODO: PGP check

- name: Unpack nginx {{nginx_file_tag}}
  command: tar -xvzf {{nginx_file_name}} chdir={{nginx_tmp_dir}}
  when: wanted_version_installed.rc == 1

- name: Compile and install nginx {{nginx_file_tag}}
  shell: ./configure && make && make install chdir={{nginx_tmp_dir}}{{nginx_file_tag}}
  sudo: true
  when: wanted_version_installed.rc == 1

- name: Create nginx default file
  template: src=nginx-default.j2 dest=/etc/default/nginx
    owner="root" group="root" mode=0654
  # when not running in a docker
  when: docker_installed.rc == 1

- name: Create Docker variant of nginx.conf file
  template: src=nginx.conf.docker.j2 dest={{nginx_install_prefix}}/conf/nginx.conf
    owner="root" group="root" mode=0744
  # when _running_ in a docker
  when: docker_installed.rc == 0

- name: Create nginx.conf file
  template: src=nginx.conf.j2 dest={{nginx_install_prefix}}/conf/nginx.conf
    owner="root" group="root" mode=0644
  # when not in a docker
  when: docker_installed.rc == 1

# == Init script ==
- name: Remove nginx-init-ubuntu script
  file: path=/etc/init.d/nginx state=absent
  # when not running in a docker
  when: docker_installed.rc == 1 or nginx_docker_override == True

# - name: Create nginx init file using local nginx-init-ubuntu script
  template: src=nginx-init-ubuntu.j2 dest=/etc/init.d/nginx
    owner="root" group="root" mode=0755
  when: nginx_use_local_init == True
  # when not in a docker or when explicitly told to via override
  # when: docker_installed.rc == 1 or nginx_docker_override == True

# Force download of master when not running in docker or
# when explicitly told to via override
- name: download nginx-init-ubuntu init script
  get_url: url=https://raw.github.com/JasonGiedymin/nginx-init-ubuntu/master/nginx
    dest=/etc/init.d/nginx
    mode=0740
    force=yes
  when: nginx_use_local_init == False
  # when not running in a docker
  # when: docker_installed.rc == 1 or nginx_docker_override == True

# Notify will fail above even with 'when' conditional (because docker)
# - name: restart nginx
#   service: name=nginx state=restarted
#   when: docker_installed.rc == 1 or nginx_docker_override == True
