---
- name: Install RedHat packages
  yum: pkg={{item}} state=present
  with_items:
    - wget
    - curl
    - gcc-c++
    - gcc
    - pcre
    - pcre-devel
    - openssl
    - openssl-devel
    - zlib
    - zlib-devel
